### ISSUE TITLE
transfer repo

### ISSUE THREAD

**Issue by mdscheuerell** [ebuhle/LCRchumIPM#22]
I think it would be best to transfer this repo away from me and over to @ebuhle. If not, perhaps one of the WDFW folks could suggest an alternative?

**Comment by ebuhle** [comment]
LOL. I can't say I was waiting for it, but I'm not surprised either. Sorry for all the spam, @mdscheuerell.

I would be happy to host this repo, but if there is a "proper" GitHub way of transferring the contents from one user to another, I'm unaware of it. @mdscheuerell, what would you suggest as the cleanest and least hacky / error-prone approach? 

The biggest problem I can see is that all the existing Issues would presumably remain here. Many of them are still open and active, and even the closed ones contain important archival material -- I was just reading through several of them when you created this one.

**Comment by mdscheuerell** [comment]
> (W)hat would you suggest as the cleanest and least hacky / error-prone approach?

It's rather straightforward and it preserves pretty much everything re access, issues, etc. You can read an overview [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository).

**Comment by mdscheuerell** [comment]
> Sorry for all the spam.

It's actually been kind of nice to eavesdrop on the conversation 😉.

**Comment by ebuhle** [comment]
> It's rather straightforward and it preserves pretty much everything re access, issues, etc. You can read an overview [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository).

Whoa, amazing! I had no idea. Well, it sounds like you would just need to transfer it to me and I would confirm the transfer. I would propose also renaming it to `/LCRchumIPM`. Presumably anyone interfacing with the repo via RStudio would need to manually update the target in Project Options?

If that's all there is to it, I say go ahead. And since you'd be automatically added as a contributor, you would still get to eavesdrop.

**Comment by ebuhle** [comment]
Success! The repo has been transferred to my account and renamed `LCRchumIPM`. 

@kalebentley @tbuehrens @Hillsont @BradGarnerWDFW If you are using RStudio, you can still push and pull without changing anything; the old origin URL will be automatically redirected. You will see a message indicating that the origin URL has changed and reminding you to update it. To do that: 

1. Go to the Git pane, click the `More` (gear) menu, then `New Terminal`.
2. Following the instructions [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository), type `git remote set-url origin <new-url>`. I use SSH to connect RStudio to GitHub, so in my case `<new-url>` is `git@github.com:ebuhle/LCRchumIPM.git`.

That's it! I'm pleasantly shocked at how painless this was. It really does just work.

So long @mdscheuerell (to your user account, anyway), and thanks for all the fish. :fishing_pole_and_fish:

**Comment by kalebentley** [comment]
Thanks @ebuhle.  When I opened the existing .Rproj file and hit "pull", I got a message saying that a bunch of files would be overwritten and so the action was aborted.   Therefore, I just moved the _chumIPM_ folder and cloned the newly created _LCRchumIPM_ repo.  Seems to have done the trick.

**Comment by mdscheuerell** [comment]
I'd have to see what the specific issue was, but I would have expected things to be overwritten unless @kalebentley did not have everything committed and pulled on his side first.
