### ISSUE TITLE
SAR reporting/summary error?

### ISSUE THREAD

**Issue by kalebentley** [ebuhle/LCRchumIPM#27]
Hey @ebuhle,
I was looking at the Marine Survival results reported in our "LCRchumIPM_analysis.html" file and noticed the written summary may be incorrect.  Specifically, the figure and written sentence report that SARs are higher for natural/wild-origin chum relative to hatchery-origin but the written percentages state the opposite (see snippet below).
Kale

![image](https://github.com/ebuhle/LCRchumIPM/assets/40397762/f6279128-8aea-44b1-9951-217ba3f99019)

**Comment by ebuhle** [comment]
Oh yes, right you are! Somewhere along the way I transposed the inline code snippets for the two posterior summary entries relative to the corresponding text phrases in that sentence. Good catch.
